" Clear status line when vimrc is reloaded.
set statusline=

" Status line left side.
set statusline+=\ %F\ %M\ %Y\ %R

" Use a divider to separate the left side from the right side.
set statusline+=%=

" Status line right side.
set statusline+=\ row:\ %l\ col:\ %c\ percent:\ %p%%

" Enable status bar
set laststatus=2

" Enable line numbers
set number

" Enable wrapping
set wrap

" Enable syntax highlighting
syntax on

" Set compatibility to Vim only
set nocompatible

" Encoding
set encoding=utf-8

